// Copyright 2026 Tree xie.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Command-stats diagnostics — "why is Redis busy".
//!
//! Polls `INFO commandstats` on a heartbeat (aggregated across all cluster
//! masters) and shows a per-command **call-rate** table computed from the
//! delta between two samples. Idle (0 rate) rows are hidden by default,
//! with search / Top-N / self-probe filters to cut noise. Counter resets
//! (`CONFIG RESETSTAT`) use saturating_sub so they read as zero rather
//! than a spike.

use crate::assets::CustomIconName;
use crate::connection::{Capability, CommandStat, get_connection_manager};
use crate::error::Error;
use crate::helpers::get_mono_font_family;
use crate::states::{
    ServerView, ZedisGlobalStore, ZedisServerState, back_to_editor_tooltip, dialog_button_props,
    escalate_dangerous_body, i18n_common, i18n_server_load,
};
use crate::views::unavailable_chip;
use gpui::{App, ClipboardItem, Context, Entity, ScrollHandle, SharedString, Task, Window, div, prelude::*, px};
use gpui_component::{
    ActiveTheme, Disableable, Icon, IconName, Sizable, StyledExt, WindowExt,
    button::{Button, ButtonVariants},
    h_flex,
    input::{Input, InputState},
    label::Label,
    notification::Notification,
    v_flex,
};
use std::cmp::Ordering;
use std::collections::HashMap;
use std::time::{Duration, Instant};
use zedis_ui::ZedisDialog;

type Result<T, E = Error> = std::result::Result<T, E>;

const POLL_SECS: u64 = 3;
const NUM_COL: f32 = 96.0;
const PCT_COL: f32 = 72.0;
const DEFAULT_TOP_N: usize = 50;
const HOT_AVG_US: f64 = 500.0;
const HOT_RATE: f64 = 10.0;

/// Commands commonly generated by Zedis itself (health + info probes).
const SELF_PROBE: &[&str] = &[
    "info",
    "ping",
    "client|setname",
    "client|setinfo",
    "command|docs",
    "command|info",
    "hello",
];

#[derive(Clone, Copy, PartialEq)]
enum SortBy {
    Command,
    Rate,
    AvgUs,
    Calls,
    UsecShare,
}

struct CmdRow {
    name: SharedString,
    rate: f64,
    avg_us: f64,
    calls: u64,
    /// Share of interval CPU-ish time (Δusec / sum Δusec), 0..=1.
    usec_share: f64,
    dcalls: u64,
}

pub struct ZedisServerLoad {
    server_state: Entity<ZedisServerState>,
    cmd_rows: Vec<CmdRow>,
    cmd_error: Option<SharedString>,
    prev: HashMap<String, (u64, u64)>,
    last_sample_at: Option<Instant>,
    has_delta: bool,
    poll_task: Option<Task<()>>,
    force_tick: bool,
    sort_by: SortBy,
    sort_desc: bool,
    show_idle: bool,
    hide_self: bool,
    /// 0 = no limit.
    top_n: usize,
    filter: Entity<InputState>,
    pending_notification: Option<Notification>,
    scroll: ScrollHandle,
}

impl ZedisServerLoad {
    pub fn new(server_state: Entity<ZedisServerState>, window: &mut Window, cx: &mut Context<Self>) -> Self {
        let filter = cx.new(|cx| {
            InputState::new(window, cx)
                .clean_on_escape()
                .placeholder(i18n_server_load(cx, "filter_placeholder").to_string())
        });
        let mut this = Self {
            server_state,
            cmd_rows: Vec::new(),
            cmd_error: None,
            prev: HashMap::new(),
            last_sample_at: None,
            has_delta: false,
            poll_task: None,
            force_tick: false,
            sort_by: SortBy::Rate,
            sort_desc: true,
            show_idle: false,
            hide_self: true,
            top_n: DEFAULT_TOP_N,
            filter,
            pending_notification: None,
            scroll: ScrollHandle::new(),
        };
        this.start_polling(cx);
        this
    }

    fn start_polling(&mut self, cx: &mut Context<Self>) {
        self.poll_task = Some(cx.spawn(async move |this, cx| {
            loop {
                let conn = match this.update(cx, |this, cx| {
                    let s = this.server_state.read(cx);
                    // A backgrounded workspace tab keeps this view alive —
                    // don't keep streaming `INFO commandstats` (a payload
                    // that scales with the number of distinct commands) for
                    // a hidden panel. On re-activation the next tick samples
                    // again; the delta then averages over the hidden window.
                    if s.is_background() {
                        return None;
                    }
                    Some((s.server_id().to_string(), s.db()))
                }) {
                    Ok(c) => c,
                    Err(_) => break,
                };
                if let Some(conn) = conn.filter(|c| !c.0.is_empty()) {
                    let result = fetch_command_stats(conn.0, conn.1).await;
                    if this
                        .update(cx, |this, cx| {
                            this.force_tick = false;
                            this.apply_command_stats(result, cx);
                        })
                        .is_err()
                    {
                        break;
                    }
                }
                // Responsive Refresh: wake every 200ms to check force_tick.
                let mut waited = 0u64;
                while waited < POLL_SECS * 1000 {
                    cx.background_executor().timer(Duration::from_millis(200)).await;
                    waited += 200;
                    let force = this.update(cx, |this, _| this.force_tick).unwrap_or(false);
                    if force {
                        break;
                    }
                }
            }
        }));
    }

    fn request_refresh(&mut self, cx: &mut Context<Self>) {
        self.force_tick = true;
        cx.notify();
    }

    fn apply_command_stats(&mut self, result: Result<Vec<CommandStat>>, cx: &mut Context<Self>) {
        match result {
            Ok(stats) => {
                let now = Instant::now();
                let had_prev = self.last_sample_at.is_some();
                let dt = self
                    .last_sample_at
                    .map(|t| now.duration_since(t).as_secs_f64())
                    .filter(|d| *d > 0.0);

                let mut interval_usec_total: u64 = 0;
                let mut interim: Vec<(String, f64, f64, u64, u64, u64)> = Vec::with_capacity(stats.len());
                for s in &stats {
                    let (pc, pu) = self.prev.get(&s.name).copied().unwrap_or((0, 0));
                    let dcalls = s.calls.saturating_sub(pc);
                    let dusec = s.usec.saturating_sub(pu);
                    interval_usec_total = interval_usec_total.saturating_add(dusec);
                    let rate = dt.map(|d| dcalls as f64 / d).unwrap_or(0.0);
                    let avg_us = if dcalls > 0 {
                        dusec as f64 / dcalls as f64
                    } else if s.calls > 0 {
                        s.usec as f64 / s.calls as f64
                    } else {
                        0.0
                    };
                    interim.push((s.name.clone(), rate, avg_us, s.calls, dcalls, dusec));
                }

                self.cmd_rows = interim
                    .into_iter()
                    .map(|(name, rate, avg_us, calls, dcalls, dusec)| {
                        let usec_share = if interval_usec_total > 0 {
                            dusec as f64 / interval_usec_total as f64
                        } else {
                            0.0
                        };
                        CmdRow {
                            name: name.into(),
                            rate,
                            avg_us,
                            calls,
                            usec_share,
                            dcalls,
                        }
                    })
                    .collect();
                self.has_delta = had_prev && dt.is_some();
                self.sort_rows();
                self.prev = stats.into_iter().map(|s| (s.name, (s.calls, s.usec))).collect();
                self.last_sample_at = Some(now);
                self.cmd_error = None;
            }
            Err(e) => self.cmd_error = Some(e.to_string().into()),
        }
        cx.notify();
    }

    fn sort_rows(&mut self) {
        let desc = self.sort_desc;
        let dir = |o: Ordering| if desc { o.reverse() } else { o };
        match self.sort_by {
            SortBy::Command => self.cmd_rows.sort_by(|a, b| dir(a.name.cmp(&b.name))),
            SortBy::Rate => self
                .cmd_rows
                .sort_by(|a, b| dir(a.rate.partial_cmp(&b.rate).unwrap_or(Ordering::Equal))),
            SortBy::AvgUs => self
                .cmd_rows
                .sort_by(|a, b| dir(a.avg_us.partial_cmp(&b.avg_us).unwrap_or(Ordering::Equal))),
            SortBy::Calls => self.cmd_rows.sort_by(|a, b| dir(a.calls.cmp(&b.calls))),
            SortBy::UsecShare => self
                .cmd_rows
                .sort_by(|a, b| dir(a.usec_share.partial_cmp(&b.usec_share).unwrap_or(Ordering::Equal))),
        }
    }

    fn set_sort(&mut self, col: SortBy, cx: &mut Context<Self>) {
        if self.sort_by == col {
            self.sort_desc = !self.sort_desc;
        } else {
            self.sort_by = col;
            self.sort_desc = col != SortBy::Command;
        }
        self.sort_rows();
        cx.notify();
    }

    fn is_self_probe(name: &str) -> bool {
        let n = name.to_ascii_lowercase();
        SELF_PROBE.iter().any(|p| n == *p)
    }

    fn filter_text(&self, cx: &App) -> String {
        self.filter.read(cx).value().to_string()
    }

    fn filtered_rows<'a>(&'a self, filter_text: &str) -> Vec<&'a CmdRow> {
        // Hide-idle mode needs an interval Δ to know "idle". Before the
        // second sample every rate is 0 and every dcalls is 0 — treating
        // that as "show everything" floods the table with historical
        // cmds, then they vanish on the next poll. Prefer empty +
        // "waiting for second sample" instead.
        if !self.show_idle && !self.has_delta {
            return Vec::new();
        }
        let q = filter_text.trim().to_ascii_lowercase();
        self.cmd_rows
            .iter()
            .filter(|r| {
                if !self.show_idle && r.rate <= 0.0 && r.dcalls == 0 {
                    return false;
                }
                if self.hide_self && Self::is_self_probe(r.name.as_ref()) {
                    return false;
                }
                if !q.is_empty() && !r.name.to_ascii_lowercase().contains(&q) {
                    return false;
                }
                true
            })
            .collect()
    }

    fn display_rows<'a>(&'a self, filter_text: &str) -> Vec<&'a CmdRow> {
        let mut rows = self.filtered_rows(filter_text);
        if self.top_n > 0 && rows.len() > self.top_n {
            rows.truncate(self.top_n);
        }
        rows
    }

    fn summary<'a>(&'a self, filter_text: &str) -> (f64, usize, Option<&'a CmdRow>, Option<&'a CmdRow>) {
        let filtered = self.filtered_rows(filter_text);
        let total_rate: f64 = filtered.iter().map(|r| r.rate).sum();
        let active = filtered.iter().filter(|r| r.rate > 0.0 || r.dcalls > 0).count();
        let hottest = filtered
            .iter()
            .filter(|r| r.rate > 0.0)
            .max_by(|a, b| a.rate.partial_cmp(&b.rate).unwrap_or(Ordering::Equal))
            .copied();
        let slowest = filtered
            .iter()
            .filter(|r| r.dcalls > 0 || r.rate > 0.0)
            .max_by(|a, b| a.avg_us.partial_cmp(&b.avg_us).unwrap_or(Ordering::Equal))
            .copied();
        (total_rate, active, hottest, slowest)
    }

    fn confirm_resetstat(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        if !self.server_state.read(cx).can(Capability::ConfigWrite) {
            self.pending_notification = Some(Notification::error(i18n_server_load(cx, "reset_readonly")));
            cx.notify();
            return;
        }
        let title = i18n_server_load(cx, "reset_title");
        let body = i18n_server_load(cx, "reset_body");
        let server_id = self.server_state.read(cx).server_id().to_string();
        let db = self.server_state.read(cx).db();
        let entity = cx.entity().downgrade();
        ZedisDialog::new_alert(title, escalate_dangerous_body(cx, &server_id, body.to_string()))
            .button_props(
                dialog_button_props(cx)
                    .ok_text(i18n_server_load(cx, "reset_confirm"))
                    .cancel_text(i18n_common(cx, "cancel")),
            )
            .on_ok(move |_, window, cx| {
                if let Some(this) = entity.upgrade() {
                    this.update(cx, |this, cx| {
                        this.run_resetstat(server_id.clone(), db, cx);
                    });
                }
                window.close_dialog(cx);
                true
            })
            .open(window, cx);
    }

    fn run_resetstat(&mut self, server_id: String, db: usize, cx: &mut Context<Self>) {
        let entity = cx.entity().downgrade();
        cx.spawn(async move |_handle, cx| {
            let task = cx.background_spawn(async move {
                let mut conn = get_connection_manager().get_connection(&server_id, db).await?;
                redis::cmd("CONFIG")
                    .arg("RESETSTAT")
                    .query_async::<()>(&mut conn)
                    .await
                    .map_err(|e| Error::Invalid { message: e.to_string() })?;
                Ok::<_, Error>(())
            });
            let result = task.await;
            let _ = entity.update(cx, |this, cx| {
                match result {
                    Ok(()) => {
                        this.prev.clear();
                        this.has_delta = false;
                        this.last_sample_at = None;
                        this.cmd_rows.clear();
                        this.pending_notification = Some(Notification::success(i18n_server_load(cx, "reset_ok")));
                        this.force_tick = true;
                    }
                    Err(e) => {
                        this.pending_notification = Some(Notification::error(e.to_string()));
                    }
                }
                cx.notify();
            });
        })
        .detach();
    }

    fn export_csv(&mut self, cx: &mut Context<Self>) {
        let q = self.filter_text(cx);
        let rows = self.display_rows(&q);
        if rows.is_empty() {
            return;
        }
        let mut out = String::from("command,calls_per_sec,usec_per_call,calls,usec_share\n");
        for r in rows {
            out.push_str(&format!(
                "{},{:.3},{:.1},{},{:.4}\n",
                r.name, r.rate, r.avg_us, r.calls, r.usec_share
            ));
        }
        cx.write_to_clipboard(ClipboardItem::new_string(out));
        self.pending_notification = Some(Notification::info(i18n_server_load(cx, "export_ok")));
        cx.notify();
    }

    fn render_summary(&self, filter_text: &str, cx: &mut Context<Self>) -> gpui::AnyElement {
        let theme = cx.theme();
        let muted = theme.muted_foreground;
        let (total_rate, active, hottest, slowest) = self.summary(filter_text);

        let sample_hint: SharedString = if !self.has_delta {
            i18n_server_load(cx, "waiting_second_sample")
        } else if let Some(t) = self.last_sample_at {
            let ago = t.elapsed().as_secs();
            let locale = cx.global::<ZedisGlobalStore>().read(cx).locale().to_string();
            rust_i18n::t!("server_load.sample_ago", secs = ago, poll = POLL_SECS, locale = locale)
                .to_string()
                .into()
        } else {
            SharedString::default()
        };

        let hot_txt: SharedString = hottest
            .map(|r| format!("{} ({:.1}/s)", r.name, r.rate))
            .unwrap_or_else(|| "—".into())
            .into();
        let slow_txt: SharedString = slowest
            .map(|r| format!("{} ({:.0} µs)", r.name, r.avg_us))
            .unwrap_or_else(|| "—".into())
            .into();

        h_flex()
            .w_full()
            .px_3()
            .py_2()
            .gap_4()
            .flex_wrap()
            .items_center()
            .border_b_1()
            .border_color(theme.border)
            .child(summary_chip(
                i18n_server_load(cx, "sum_rate"),
                format!("{total_rate:.1}/s"),
                theme.foreground,
                muted,
            ))
            .child(summary_chip(
                i18n_server_load(cx, "sum_active"),
                active.to_string(),
                theme.foreground,
                muted,
            ))
            .child(summary_chip(
                i18n_server_load(cx, "sum_hottest"),
                hot_txt,
                theme.warning,
                muted,
            ))
            .child(summary_chip(
                i18n_server_load(cx, "sum_slowest"),
                slow_txt,
                theme.yellow,
                muted,
            ))
            .child(div().flex_1())
            .child(Label::new(sample_hint).text_xs().text_color(muted))
            .into_any_element()
    }

    fn render_toolbar(&self, cx: &mut Context<Self>) -> gpui::AnyElement {
        let theme = cx.theme();
        let can_write = self.server_state.read(cx).can(Capability::ConfigWrite);
        h_flex()
            .w_full()
            .px_3()
            .py_2()
            .gap_2()
            .items_center()
            .flex_wrap()
            .border_b_1()
            .border_color(theme.border)
            .child(
                div()
                    .w(px(200.))
                    .child(Input::new(&self.filter).appearance(true).small()),
            )
            .child(
                Button::new("sl-show-idle")
                    .xsmall()
                    .when(self.show_idle, |b| b.primary())
                    .when(!self.show_idle, |b| b.outline())
                    .label(i18n_server_load(cx, "show_idle"))
                    .tooltip(i18n_server_load(cx, "show_idle_tooltip"))
                    .on_click(cx.listener(|this, _, _w, cx| {
                        this.show_idle = !this.show_idle;
                        cx.notify();
                    })),
            )
            .child(
                Button::new("sl-hide-self")
                    .xsmall()
                    .when(self.hide_self, |b| b.primary())
                    .when(!self.hide_self, |b| b.outline())
                    .label(i18n_server_load(cx, "hide_self"))
                    .tooltip(i18n_server_load(cx, "hide_self_tooltip"))
                    .on_click(cx.listener(|this, _, _w, cx| {
                        this.hide_self = !this.hide_self;
                        cx.notify();
                    })),
            )
            .child(
                Button::new("sl-top-25")
                    .xsmall()
                    .when(self.top_n == 25, |b| b.primary())
                    .when(self.top_n != 25, |b| b.outline())
                    .label("Top 25")
                    .on_click(cx.listener(|this, _, _w, cx| {
                        this.top_n = 25;
                        cx.notify();
                    })),
            )
            .child(
                Button::new("sl-top-50")
                    .xsmall()
                    .when(self.top_n == 50, |b| b.primary())
                    .when(self.top_n != 50, |b| b.outline())
                    .label("Top 50")
                    .on_click(cx.listener(|this, _, _w, cx| {
                        this.top_n = 50;
                        cx.notify();
                    })),
            )
            .child(
                Button::new("sl-top-all")
                    .xsmall()
                    .when(self.top_n == 0, |b| b.primary())
                    .when(self.top_n != 0, |b| b.outline())
                    .label(i18n_server_load(cx, "top_all"))
                    .on_click(cx.listener(|this, _, _w, cx| {
                        this.top_n = 0;
                        cx.notify();
                    })),
            )
            .child(div().flex_1())
            .child(
                Button::new("sl-export")
                    .ghost()
                    .small()
                    .label(i18n_server_load(cx, "export"))
                    .tooltip(i18n_server_load(cx, "export_tooltip"))
                    .disabled(self.cmd_rows.is_empty())
                    .on_click(cx.listener(|this, _, _w, cx| this.export_csv(cx))),
            )
            .when(can_write, |this| {
                this.child(
                    Button::new("sl-reset")
                        .ghost()
                        .small()
                        .label(i18n_server_load(cx, "reset"))
                        .tooltip(i18n_server_load(cx, "reset_tooltip"))
                        .on_click(cx.listener(|this, _, w, cx| this.confirm_resetstat(w, cx))),
                )
            })
            // CONFIG RESETSTAT goes with CONFIG SET: when the server denies
            // configuration writes, name the reason where the button was.
            .when_some(
                self.server_state.read(cx).blocked_by(Capability::ConfigWrite),
                |this, (command, status)| this.child(unavailable_chip(cx, command, status)),
            )
            .child(
                Button::new("sl-refresh")
                    .outline()
                    .small()
                    .icon(Icon::new(CustomIconName::RotateCw))
                    .tooltip(i18n_server_load(cx, "refresh_tooltip"))
                    .on_click(cx.listener(|this, _, _w, cx| this.request_refresh(cx))),
            )
            .into_any_element()
    }

    fn render_table(&self, filter_text: &str, cx: &mut Context<Self>) -> gpui::AnyElement {
        let muted = cx.theme().muted_foreground;
        let theme = cx.theme();
        if let Some(err) = self.cmd_error.clone() {
            return div()
                .p_4()
                .child(Label::new(err).text_sm().text_color(theme.danger))
                .into_any_element();
        }
        if self.cmd_rows.is_empty() {
            return div()
                .p_4()
                .child(Label::new(i18n_server_load(cx, "loading")).text_sm().text_color(muted))
                .into_any_element();
        }

        let display = self.display_rows(filter_text);
        if display.is_empty() {
            return div()
                .p_4()
                .child(
                    Label::new(if !self.has_delta {
                        i18n_server_load(cx, "waiting_second_sample")
                    } else {
                        i18n_server_load(cx, "empty_filtered")
                    })
                    .text_sm()
                    .text_color(muted),
                )
                .into_any_element();
        }

        let fg = theme.foreground;
        let active = self.sort_by;
        let desc = self.sort_desc;
        let arrow = |col: SortBy| {
            if active == col {
                if desc { " ↓" } else { " ↑" }
            } else {
                ""
            }
        };
        let head_color = |col: SortBy| if active == col { fg } else { muted };

        let header = h_flex()
            .w_full()
            .px_3()
            .py_1p5()
            .gap_2()
            .items_center()
            .border_b_1()
            .border_color(theme.border)
            .child(
                div()
                    .id("sl-hdr-command")
                    .flex_1()
                    .min_w_0()
                    .cursor_pointer()
                    .on_click(cx.listener(|this, _, _w, cx| this.set_sort(SortBy::Command, cx)))
                    .child(
                        Label::new(format!(
                            "{}{}",
                            i18n_server_load(cx, "col_command"),
                            arrow(SortBy::Command)
                        ))
                        .text_xs()
                        .text_color(head_color(SortBy::Command)),
                    ),
            )
            .child(
                h_flex()
                    .id("sl-hdr-rate")
                    .w(px(NUM_COL))
                    .justify_end()
                    .cursor_pointer()
                    .on_click(cx.listener(|this, _, _w, cx| this.set_sort(SortBy::Rate, cx)))
                    .child(
                        Label::new(format!("{}{}", i18n_server_load(cx, "col_rate"), arrow(SortBy::Rate)))
                            .text_xs()
                            .text_color(head_color(SortBy::Rate)),
                    ),
            )
            .child(
                h_flex()
                    .id("sl-hdr-avg")
                    .w(px(NUM_COL))
                    .justify_end()
                    .cursor_pointer()
                    .on_click(cx.listener(|this, _, _w, cx| this.set_sort(SortBy::AvgUs, cx)))
                    .child(
                        Label::new(format!("{}{}", i18n_server_load(cx, "col_avg"), arrow(SortBy::AvgUs)))
                            .text_xs()
                            .text_color(head_color(SortBy::AvgUs)),
                    ),
            )
            .child(
                h_flex()
                    .id("sl-hdr-share")
                    .w(px(PCT_COL))
                    .justify_end()
                    .cursor_pointer()
                    .on_click(cx.listener(|this, _, _w, cx| this.set_sort(SortBy::UsecShare, cx)))
                    .child(
                        Label::new(format!(
                            "{}{}",
                            i18n_server_load(cx, "col_share"),
                            arrow(SortBy::UsecShare)
                        ))
                        .text_xs()
                        .text_color(head_color(SortBy::UsecShare)),
                    ),
            )
            .child(
                h_flex()
                    .id("sl-hdr-calls")
                    .w(px(NUM_COL))
                    .justify_end()
                    .cursor_pointer()
                    .on_click(cx.listener(|this, _, _w, cx| this.set_sort(SortBy::Calls, cx)))
                    .child(
                        Label::new(format!("{}{}", i18n_server_load(cx, "col_calls"), arrow(SortBy::Calls)))
                            .text_xs()
                            .text_color(head_color(SortBy::Calls)),
                    ),
            );

        let stripe_bg = theme.table_even;
        let warning = theme.warning;
        let yellow = theme.yellow;
        let mut list = v_flex().w_full().child(header);
        for (row_ix, r) in display.into_iter().enumerate() {
            let is_stripe = row_ix % 2 != 0;
            let hot_rate = r.rate >= HOT_RATE;
            let hot_avg = r.avg_us >= HOT_AVG_US && (r.dcalls > 0 || r.rate > 0.0);
            let rate_color = if hot_rate { warning } else { fg };
            let avg_color = if hot_avg { yellow } else { muted };

            list = list.child(
                h_flex()
                    .w_full()
                    .px_3()
                    .py_1()
                    .gap_2()
                    .items_center()
                    .when(is_stripe && !(hot_rate || hot_avg), |this| this.bg(stripe_bg))
                    .when(hot_rate || hot_avg, |this| this.bg(warning.opacity(0.08)))
                    .child(
                        div()
                            .flex_1()
                            .min_w_0()
                            .child(Label::new(r.name.clone()).text_xs().truncate()),
                    )
                    .child(
                        h_flex().w(px(NUM_COL)).justify_end().child(
                            Label::new(format!("{:.1}/s", r.rate))
                                .text_xs()
                                .font_semibold()
                                .text_color(rate_color),
                        ),
                    )
                    .child(
                        h_flex().w(px(NUM_COL)).justify_end().child(
                            Label::new(format!("{:.0} µs", r.avg_us))
                                .text_xs()
                                .text_color(avg_color),
                        ),
                    )
                    .child(
                        h_flex().w(px(PCT_COL)).justify_end().child(
                            Label::new(format!("{:.1}%", r.usec_share * 100.0))
                                .text_xs()
                                .text_color(muted),
                        ),
                    )
                    .child(
                        h_flex()
                            .w(px(NUM_COL))
                            .justify_end()
                            .child(Label::new(format_count(r.calls)).text_xs().text_color(muted)),
                    ),
            );
        }

        let filtered_n = self.filtered_rows(filter_text).len();
        let total_n = self.cmd_rows.len();
        let shown = self.display_rows(filter_text).len();
        let locale = cx.global::<ZedisGlobalStore>().read(cx).locale().to_string();
        let footer: SharedString = rust_i18n::t!(
            "server_load.footer_showing",
            shown = shown,
            filtered = filtered_n,
            total = total_n,
            locale = locale
        )
        .to_string()
        .into();

        v_flex()
            .w_full()
            .child(list)
            .child(
                div()
                    .px_3()
                    .py_1()
                    .border_t_1()
                    .border_color(theme.border)
                    .child(Label::new(footer).text_xs().text_color(muted)),
            )
            .into_any_element()
    }
}

fn summary_chip(
    label: SharedString,
    value: impl Into<SharedString>,
    value_color: gpui::Hsla,
    muted: gpui::Hsla,
) -> impl IntoElement {
    v_flex()
        .gap_0p5()
        .child(Label::new(label).text_xs().text_color(muted))
        .child(
            Label::new(value.into())
                .text_sm()
                .font_semibold()
                .text_color(value_color),
        )
}

fn format_count(n: u64) -> String {
    if n >= 1_000_000 {
        format!("{:.1}M", n as f64 / 1_000_000.0)
    } else if n >= 10_000 {
        format!("{:.1}k", n as f64 / 1_000.0)
    } else {
        n.to_string()
    }
}

impl Render for ZedisServerLoad {
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        if let Some(n) = self.pending_notification.take() {
            window.push_notification(n, cx);
        }
        let filter_text = self.filter_text(cx);
        let body = self.render_table(&filter_text, cx);
        let summary = self.render_summary(&filter_text, cx);
        let toolbar = self.render_toolbar(cx);

        v_flex()
            .size_full()
            .font_family(get_mono_font_family())
            .child(
                h_flex()
                    .items_center()
                    .gap_2()
                    .px_3()
                    .py_2()
                    .border_b_1()
                    .border_color(cx.theme().border)
                    .child(
                        Button::new("server-load-back")
                            .ghost()
                            .small()
                            .icon(IconName::ArrowLeft)
                            .tooltip(back_to_editor_tooltip(cx))
                            .on_click(|_, _w, cx| {
                                cx.update_global::<ZedisGlobalStore, ()>(|store, cx| {
                                    store.update(cx, |state, cx| state.go_to_view(ServerView::Editor, cx));
                                });
                            }),
                    )
                    .child(Label::new(i18n_server_load(cx, "title")).font_semibold())
                    .child(div().flex_1())
                    .child(
                        Label::new(i18n_server_load(cx, "help_hint"))
                            .text_xs()
                            .text_color(cx.theme().muted_foreground),
                    ),
            )
            .child(summary)
            .child(toolbar)
            .child(
                div()
                    .id("server-load-body")
                    .flex_1()
                    .min_h_0()
                    .w_full()
                    .overflow_y_scroll()
                    .track_scroll(&self.scroll)
                    .child(body),
            )
    }
}

async fn fetch_command_stats(server_id: String, db: usize) -> Result<Vec<CommandStat>> {
    let client = get_connection_manager().get_client(&server_id, db).await?;
    Ok(client.command_stats().await?)
}
