name: "Lint"
on:
    push:
      branches: [ "**" ]
    pull_request:
      branches: [ "**" ]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.95.0
  APP_NAME: Zedis

jobs:
  macos:
    name: macos-${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-15-intel
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - name: install tools
        run: |
          rustup update
          rustup component add clippy rustfmt
          cargo install typos-cli
      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: macos-lint-${{ matrix.target }}
      - name: lint
        run: |
          cargo fmt --check
          make lint